sudo: false

language: node_js

node_js:
  - 13

cache:
  yarn: true

script:
  - bash run-tests

deploy:
  provider: script
  skip_cleanup: true
  script:
    - bash release
  on:
    branch: master

addons:
  apt:
    update: true
