sudo: false

language: node_js

node_js:
  - "10"

cache:
  yarn: true

script:
  - bash test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - bash release
  on:
    branch: master

addons:
  apt:
    update: true

