#!/bin/bash -eu

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=./utils-env
. "$self_path/utils-env" --

log "running shellcheck"

shellcheck_cmd="shellcheck --external-sources --shell=bash"

$shellcheck_cmd \
    "$self_path/start" \
    "$self_path/release" \
    "$self_path/run-tests" \
    "$self_path/utils-env"

$shellcheck_cmd "$self_path/installs"/*/*
$shellcheck_cmd "$self_path/tests"/*
$shellcheck_cmd "$self_path/utils"/*

status=0

for test_path in "$self_path/tests"/*; do
    test_name="$(basename "$test_path")"

    chmod u+x "$test_path"

    if "$test_path"; then
        log "^$test_name^ passed"
    else
        status=1
        log --error "^$test_name^ failed"
    fi
done

exit $status
