#!/bin/bash -eu

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=./utils-env
. "$self_path/utils-env" --

if [ "$EUID" -ne 0 ]; then
    log --error "please run as root"
    exit 1
fi

user_name=

while [ $# -gt 0 ]; do
    case "$1" in
        -u|--user)
            user_name="${2:-}"
            shift
            ;;
    esac

    shift ||:
done

if [ -z "$user_name" ]; then
    log --error "please specify a user with the ^--user^ flag"
    exit 1
elif ! user-exists "$user_name"; then
    log --error "user $user_name doesn't seem to exist"
    exit 1
elif [ -z "$(user-home "$user_name")" ]; then
    log --error "user $user_name doesn't seem to have a home directory"
    exit 1
fi

terminal="$(tty)"
utils_path="$(location-of utils)"
installs_path="$(location-of installs)"
install_scripts="$(ls "$installs_path")"
script_list=

while true; do
    script_list=$(pick-from "$install_scripts" 2>"$terminal")

    if [ -z "$script_list" ]; then
        echo "You didn't selected any additional script."
    else
        tstyle "Additional script: **$(echo "$script_list" | strjoin ", ")**."
    fi

    ask "Do you confirm?" && break
done

add_sudoer=false
enable_autologin=false

ask -Yn "Do you want to add $user_name in ^/etc/sudoers^?" && add_sudoer=true
ask -yN "Do you want to enable autologin with for $user_name?" && enable_autologin=true

log "apt-get ^update^"
apt-get --yes update

log "apt-get ^dist-upgrade^"
apt-get --yes dist-upgrade

install-base-packages

if [ -n "$(command -v apt-file)" ]; then
    log "apt-file ^update^"
    apt-file update
fi

$add_sudoer && add-sudoer --user "$user_name"
$enable_autologin && set-autologin --user "$user_name"

[ -n "$script_list" ] && run-install "$script_list" --user "$user_name"

sudo -nu "$user_name" bash -c "PATH=\"$PATH\" \"$utils_path/restore-home-env\""
