#!/bin/bash -eu

utils_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/utils" && pwd)"

chmod u+x "$utils_dir"/*

if [ "$(echo "$PATH" | grep -c "$utils_dir")" -lt 1 ]; then
    export PATH="$PATH:$utils_dir"
fi

function read-heredoc {
    if [ -z "$1" ]; then
        log --error "empty variable in **$(basename "$0")**"
        return 1
    else
        read -r -d '' "$1" ||:
    fi
}

export -f read-heredoc

cmd="${1:-}"

if [ -n "$cmd" ]; then
    "$utils_dir/$cmd" "${@:2}"

    exit $?
fi
