#!/bin/bash -eu

if max a &>/dev/null; then
    log --error "**max** should not accept non-numeric expressions"
    exit 1;
fi

[ "$(max 1 2 3)" -eq 3 ]
[ "$(max 3 2 1)" -eq 3 ]
[ "$(max 1 3 2)" -eq 3 ]
[ "$(echo 1 2 3 | max)" -eq 3 ]
[ "$(printf '1\n2\n3\n' | max)" -eq 3 ]
