#!/bin/bash -eu

if min a &>/dev/null; then
    log --error "**min** should not accept non-numeric expressions"
    exit 1;
fi

[ "$(min 1 2 3)" -eq 1 ]
[ "$(min 3 2 1)" -eq 1 ]
[ "$(min 1 3 2)" -eq 1 ]
[ "$(echo 1 2 3 | min)" -eq 1 ]
[ "$(printf "1\n2\n3\n" | min)" -eq 1 ]
