#!/bin/bash -eu

if [ "$EUID" -ne 0 ]; then
    log --error "please run as root"
    exit 1
fi

packages=$(cat <<EOF
jq
bc
ntp
vim
git
sudo
curl
nmap
whois
xclip
gdebi
rsync
evince
strace
screen
nethogs
gparted
dirmngr
apt-src
apt-file
dnsutils
seahorse
net-tools
gddrescue
xarchiver
pulseaudio
unrar-free
lm-sensors
simple-scan
transmission
inotify-tools
gvfs-backends
poppler-utils
apt-transport-https
software-properties-common
gtk2-engines-murrine
gtk2-engines-pixbuf
gtk3-engines-xfce
numix-gtk-theme
EOF
)

log "installing base packages"
# shellcheck disable=SC2086
echo $packages

# shellcheck disable=SC2086
apt-get --yes install $packages
